// Regenerates app/utils/mapDots.ts (the dotted world map in the About section).
//
// Usage:
//   npm i -D world-atlas@2 topojson-client d3-geo
//   node scripts/mapgen.mjs
//
// The generated file is committed, so these packages are not part of the
// project's regular devDependencies.

import { readFileSync, writeFileSync } from "node:fs"
import * as topojson from "topojson-client"
import { geoContains } from "d3-geo"

const world = JSON.parse(
  readFileSync(
    new URL("../node_modules/world-atlas/land-110m.json", import.meta.url),
    "utf8"
  )
)
const land = topojson.feature(world, world.objects.land)

// Equirectangular grid, clipped to 62°N–56°S (crops Antarctica/high Arctic)
const W = 880
const H = 440
const STEP = 2.0 // degrees between dots

const dots = []
for (let lat = 62; lat >= -56; lat -= STEP) {
  for (let lon = -168; lon <= 180; lon += STEP) {
    if (geoContains(land, [lon, lat])) {
      const x = ((lon + 180) / 360) * W
      const y = ((90 - lat) / 180) * H
      dots.push(`M${x.toFixed(1)} ${y.toFixed(1)}h0`)
    }
  }
}

// Kuala Lumpur marker, as percentages of the viewBox
const klx = (((101.6869 + 180) / 360) * 100).toFixed(2)
const kly = (((90 - 3.139) / 180) * 100).toFixed(2)

const out = `// Generated by scripts/mapgen.mjs from world-atlas land-110m
// (equirectangular projection, ${STEP}° dot grid). Do not edit by hand.
export const MAP_VIEWBOX = "0 0 ${W} ${H}"
export const MAP_PIN = { x: ${klx}, y: ${kly} } // Kuala Lumpur, %
export const MAP_DOTS =
  "${dots.join("")}"
`

writeFileSync(new URL("../app/utils/mapDots.ts", import.meta.url), out)
console.log(`Wrote ${dots.length} dots to app/utils/mapDots.ts`)
